// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AlertConnection struct {
	Edges    []*AlertEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type AlertEdge struct {
	Cursor string           `json:"cursor"`
	Node   *AlertOccurrence `json:"node"`
}

type AlertOccurrence struct {
	ID                 string              `json:"id"`
	DeviceID           string              `json:"deviceId"`
	RuleID             string              `json:"ruleId"`
	MessageID          string              `json:"messageId"`
	ObservedAt         time.Time           `json:"observedAt"`
	ReceivedAt         time.Time           `json:"receivedAt"`
	TemperatureCelsius float64             `json:"temperatureCelsius"`
	Metric             ThresholdMetric     `json:"metric"`
	Comparator         ThresholdComparator `json:"comparator"`
	ThresholdCelsius   float64             `json:"thresholdCelsius"`
	CreatedAt          time.Time           `json:"createdAt"`
}

type Command struct {
	ID             string              `json:"id"`
	DeviceID       string              `json:"deviceId"`
	Type           CommandType         `json:"type"`
	Status         CommandStatus       `json:"status"`
	CreatedAt      time.Time           `json:"createdAt"`
	UpdatedAt      time.Time           `json:"updatedAt"`
	ExpiresAt      time.Time           `json:"expiresAt"`
	DispatchedAt   *time.Time          `json:"dispatchedAt,omitempty"`
	AcknowledgedAt *time.Time          `json:"acknowledgedAt,omitempty"`
	TerminalAt     *time.Time          `json:"terminalAt,omitempty"`
	FailureCode    *CommandFailureCode `json:"failureCode,omitempty"`
}

type CommandConnection struct {
	Edges    []*CommandEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommandEdge struct {
	Cursor string   `json:"cursor"`
	Node   *Command `json:"node"`
}

type CreateCommandInput struct {
	DeviceID       string      `json:"deviceId"`
	Type           CommandType `json:"type"`
	IdempotencyKey string      `json:"idempotencyKey"`
}

type CreateDeviceInput struct {
	DeviceKey   string `json:"deviceKey"`
	DisplayName string `json:"displayName"`
}

type CreateThresholdRuleInput struct {
	DeviceID         string              `json:"deviceId"`
	Comparator       ThresholdComparator `json:"comparator"`
	ThresholdCelsius float64             `json:"thresholdCelsius"`
	Enabled          bool                `json:"enabled"`
}

type Device struct {
	ID          string    `json:"id"`
	DeviceKey   string    `json:"deviceKey"`
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
}

type DeviceConnection struct {
	Edges    []*DeviceEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type DeviceCurrentState struct {
	MessageID          string    `json:"messageId"`
	ObservedAt         time.Time `json:"observedAt"`
	ReceivedAt         time.Time `json:"receivedAt"`
	TemperatureCelsius float64   `json:"temperatureCelsius"`
	LastSeenAt         time.Time `json:"lastSeenAt"`
}

type DeviceEdge struct {
	Cursor string  `json:"cursor"`
	Node   *Device `json:"node"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Query struct {
}

type TelemetryConnection struct {
	Edges    []*TelemetryEdge `json:"edges"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type TelemetryEdge struct {
	Cursor string          `json:"cursor"`
	Node   *TelemetryPoint `json:"node"`
}

type TelemetryPoint struct {
	MessageID          string    `json:"messageId"`
	ObservedAt         time.Time `json:"observedAt"`
	ReceivedAt         time.Time `json:"receivedAt"`
	TemperatureCelsius float64   `json:"temperatureCelsius"`
}

type ThresholdRule struct {
	ID               string              `json:"id"`
	DeviceID         string              `json:"deviceId"`
	Metric           ThresholdMetric     `json:"metric"`
	Comparator       ThresholdComparator `json:"comparator"`
	ThresholdCelsius float64             `json:"thresholdCelsius"`
	Enabled          bool                `json:"enabled"`
	Revision         int                 `json:"revision"`
	CreatedAt        time.Time           `json:"createdAt"`
	UpdatedAt        time.Time           `json:"updatedAt"`
}

type UpdateThresholdRuleInput struct {
	ID               string              `json:"id"`
	ExpectedRevision int                 `json:"expectedRevision"`
	Comparator       ThresholdComparator `json:"comparator"`
	ThresholdCelsius float64             `json:"thresholdCelsius"`
	Enabled          bool                `json:"enabled"`
}

type CommandFailureCode string

const (
	CommandFailureCodeDeviceReportedFailure CommandFailureCode = "DEVICE_REPORTED_FAILURE"
	CommandFailureCodeDeliveryFailed        CommandFailureCode = "DELIVERY_FAILED"
)

var AllCommandFailureCode = []CommandFailureCode{
	CommandFailureCodeDeviceReportedFailure,
	CommandFailureCodeDeliveryFailed,
}

func (e CommandFailureCode) IsValid() bool {
	switch e {
	case CommandFailureCodeDeviceReportedFailure, CommandFailureCodeDeliveryFailed:
		return true
	}
	return false
}

func (e CommandFailureCode) String() string {
	return string(e)
}

func (e *CommandFailureCode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommandFailureCode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommandFailureCode", str)
	}
	return nil
}

func (e CommandFailureCode) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommandFailureCode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommandFailureCode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommandStatus string

const (
	CommandStatusPending      CommandStatus = "PENDING"
	CommandStatusDispatched   CommandStatus = "DISPATCHED"
	CommandStatusAcknowledged CommandStatus = "ACKNOWLEDGED"
	CommandStatusCompleted    CommandStatus = "COMPLETED"
	CommandStatusFailed       CommandStatus = "FAILED"
	CommandStatusTimedOut     CommandStatus = "TIMED_OUT"
)

var AllCommandStatus = []CommandStatus{
	CommandStatusPending,
	CommandStatusDispatched,
	CommandStatusAcknowledged,
	CommandStatusCompleted,
	CommandStatusFailed,
	CommandStatusTimedOut,
}

func (e CommandStatus) IsValid() bool {
	switch e {
	case CommandStatusPending, CommandStatusDispatched, CommandStatusAcknowledged, CommandStatusCompleted, CommandStatusFailed, CommandStatusTimedOut:
		return true
	}
	return false
}

func (e CommandStatus) String() string {
	return string(e)
}

func (e *CommandStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommandStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommandStatus", str)
	}
	return nil
}

func (e CommandStatus) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommandStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommandStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommandType string

const (
	CommandTypePing CommandType = "PING"
)

var AllCommandType = []CommandType{
	CommandTypePing,
}

func (e CommandType) IsValid() bool {
	switch e {
	case CommandTypePing:
		return true
	}
	return false
}

func (e CommandType) String() string {
	return string(e)
}

func (e *CommandType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommandType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommandType", str)
	}
	return nil
}

func (e CommandType) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommandType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommandType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ThresholdComparator string

const (
	ThresholdComparatorGt  ThresholdComparator = "GT"
	ThresholdComparatorGte ThresholdComparator = "GTE"
	ThresholdComparatorLt  ThresholdComparator = "LT"
	ThresholdComparatorLte ThresholdComparator = "LTE"
)

var AllThresholdComparator = []ThresholdComparator{
	ThresholdComparatorGt,
	ThresholdComparatorGte,
	ThresholdComparatorLt,
	ThresholdComparatorLte,
}

func (e ThresholdComparator) IsValid() bool {
	switch e {
	case ThresholdComparatorGt, ThresholdComparatorGte, ThresholdComparatorLt, ThresholdComparatorLte:
		return true
	}
	return false
}

func (e ThresholdComparator) String() string {
	return string(e)
}

func (e *ThresholdComparator) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ThresholdComparator(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ThresholdComparator", str)
	}
	return nil
}

func (e ThresholdComparator) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ThresholdComparator) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ThresholdComparator) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ThresholdMetric string

const (
	ThresholdMetricTemperatureCelsius ThresholdMetric = "TEMPERATURE_CELSIUS"
)

var AllThresholdMetric = []ThresholdMetric{
	ThresholdMetricTemperatureCelsius,
}

func (e ThresholdMetric) IsValid() bool {
	switch e {
	case ThresholdMetricTemperatureCelsius:
		return true
	}
	return false
}

func (e ThresholdMetric) String() string {
	return string(e)
}

func (e *ThresholdMetric) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ThresholdMetric(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ThresholdMetric", str)
	}
	return nil
}

func (e ThresholdMetric) MarshalGQL(w io.Writer) {
	_, _ = fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ThresholdMetric) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ThresholdMetric) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
