// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type CreateDeviceInput struct {
	DeviceKey   string `json:"deviceKey"`
	DisplayName string `json:"displayName"`
}

type Device struct {
	ID          string    `json:"id"`
	DeviceKey   string    `json:"deviceKey"`
	DisplayName string    `json:"displayName"`
	CreatedAt   time.Time `json:"createdAt"`
}

type DeviceConnection struct {
	Edges    []*DeviceEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type DeviceCurrentState struct {
	MessageID          string    `json:"messageId"`
	ObservedAt         time.Time `json:"observedAt"`
	ReceivedAt         time.Time `json:"receivedAt"`
	TemperatureCelsius float64   `json:"temperatureCelsius"`
	LastSeenAt         time.Time `json:"lastSeenAt"`
}

type DeviceEdge struct {
	Cursor string  `json:"cursor"`
	Node   *Device `json:"node"`
}

type Mutation struct {
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Query struct {
}

type TelemetryConnection struct {
	Edges    []*TelemetryEdge `json:"edges"`
	PageInfo *PageInfo        `json:"pageInfo"`
}

type TelemetryEdge struct {
	Cursor string          `json:"cursor"`
	Node   *TelemetryPoint `json:"node"`
}

type TelemetryPoint struct {
	MessageID          string    `json:"messageId"`
	ObservedAt         time.Time `json:"observedAt"`
	ReceivedAt         time.Time `json:"receivedAt"`
	TemperatureCelsius float64   `json:"temperatureCelsius"`
}
