package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"time"

	"github.com/methat-ruk/pulsegrid/apps/api/graph/model"
	"github.com/methat-ruk/pulsegrid/apps/api/internal/commands"
	"github.com/methat-ruk/pulsegrid/apps/api/internal/platform/requestcontext"
)

// CreateCommand is the resolver for the createCommand field.
func (r *mutationResolver) CreateCommand(ctx context.Context, input model.CreateCommandInput) (*model.Command, error) {
	organizationID, err := r.authority(ctx)
	if err != nil {
		return nil, err
	}
	repository, err := r.commandRepositoryForMutation()
	if err != nil {
		return nil, err
	}
	deviceID, err := parseCanonicalUUID(input.DeviceID)
	if err != nil {
		return nil, err
	}
	idempotencyKey, err := parseCanonicalUUID(input.IdempotencyKey)
	if err != nil {
		return nil, err
	}
	created, err := repository.Create(ctx, organizationID, commands.CreateInput{
		DeviceID:       deviceID,
		Type:           commands.Type(input.Type),
		IdempotencyKey: idempotencyKey,
		RequestID:      requestcontext.RequestID(ctx),
	})
	if err != nil {
		return nil, presentCommandMutationError(err)
	}
	return presentCommand(created), nil
}

// Command is the resolver for the command field.
func (r *queryResolver) Command(ctx context.Context, id string) (*model.Command, error) {
	organizationID, err := r.authority(ctx)
	if err != nil {
		return nil, err
	}
	repository, err := r.commandRepositoryForQuery()
	if err != nil {
		return nil, err
	}
	commandID, err := parseCanonicalUUID(id)
	if err != nil {
		return nil, err
	}
	command, err := repository.Get(ctx, organizationID, commandID)
	if errors.Is(err, commands.ErrNotFound) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return presentCommand(command), nil
}

// DeviceCommands is the resolver for the deviceCommands field.
func (r *queryResolver) DeviceCommands(ctx context.Context, deviceID string, first int, after *string) (*model.CommandConnection, error) {
	organizationID, err := r.authority(ctx)
	if err != nil {
		return nil, err
	}
	repository, err := r.commandRepositoryForQuery()
	if err != nil {
		return nil, err
	}
	parsedDeviceID, err := parseCanonicalUUID(deviceID)
	if err != nil {
		return nil, err
	}
	if first < 1 || first > commands.MaxPageSize {
		return nil, newPublicError(errorCodeBadUserInput, "first must be between 1 and 100", commands.ErrInvalidInput)
	}
	var cursor *commands.Cursor
	if after != nil {
		cursor, err = decodeCommandCursor(*after, organizationID, parsedDeviceID)
		if err != nil {
			return nil, err
		}
	}
	page, err := repository.List(ctx, organizationID, parsedDeviceID, first, cursor)
	if err != nil {
		if errors.Is(err, commands.ErrInvalidInput) {
			return nil, newPublicError(errorCodeBadUserInput, "command query input is invalid", err)
		}
		return nil, err
	}
	edges := make([]*model.CommandEdge, 0, len(page.Commands))
	for _, command := range page.Commands {
		commandCursor, cursorErr := encodeCommandCursor(commands.Cursor{CreatedAt: command.CreatedAt, ID: command.ID}, organizationID, parsedDeviceID)
		if cursorErr != nil {
			return nil, cursorErr
		}
		edges = append(edges, &model.CommandEdge{Cursor: commandCursor, Node: presentCommand(command)})
	}
	pageInfo := &model.PageInfo{HasNextPage: page.NextCursor != nil}
	if len(edges) > 0 {
		endCursor := edges[len(edges)-1].Cursor
		pageInfo.EndCursor = &endCursor
	}
	return &model.CommandConnection{Edges: edges, PageInfo: pageInfo}, nil
}

func (r *Resolver) commandRepositoryForQuery() (CommandRepository, error) {
	if r.commandRepository == nil {
		return nil, newPublicError(errorCodeInternal, "command repository is unavailable", errors.New("command repository is not configured"))
	}
	return r.commandRepository, nil
}

func (r *Resolver) commandRepositoryForMutation() (CommandRepository, error) {
	return r.commandRepositoryForQuery()
}

func presentCommandMutationError(err error) error {
	switch {
	case errors.Is(err, commands.ErrInvalidInput), errors.Is(err, commands.ErrNotFound):
		return newPublicError(errorCodeBadUserInput, "command input is invalid", err)
	case errors.Is(err, commands.ErrConflict):
		return newPublicError(errorCodeConflict, "command conflicts with current state", err)
	default:
		return err
	}
}

func presentCommand(command commands.Command) *model.Command {
	var failureCode *model.CommandFailureCode
	if command.FailureCode != nil {
		mapped := model.CommandFailureCode(*command.FailureCode)
		failureCode = &mapped
	}
	return &model.Command{
		ID:             command.ID.String(),
		DeviceID:       command.DeviceID.String(),
		Type:           model.CommandType(command.Type),
		Status:         model.CommandStatus(command.Status),
		CreatedAt:      command.CreatedAt.UTC(),
		UpdatedAt:      command.UpdatedAt.UTC(),
		ExpiresAt:      command.ExpiresAt.UTC(),
		DispatchedAt:   cloneTime(command.DispatchedAt),
		AcknowledgedAt: cloneTime(command.AcknowledgedAt),
		TerminalAt:     cloneTime(command.TerminalAt),
		FailureCode:    failureCode,
	}
}

func cloneTime(value *time.Time) *time.Time {
	if value == nil {
		return nil
	}
	cloned := value.UTC()
	return &cloned
}
