scalar Time

type Device {
  id: ID!
  deviceKey: String!
  displayName: String!
  createdAt: Time!
}

type DeviceEdge {
  cursor: String!
  node: Device!
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
}

type DeviceConnection {
  edges: [DeviceEdge!]!
  pageInfo: PageInfo!
}

input CreateDeviceInput {
  deviceKey: String!
  displayName: String!
}

type Query {
  device(id: ID!): Device
  devices(first: Int! = 20, after: String): DeviceConnection!
}

type Mutation {
  createDevice(input: CreateDeviceInput!): Device!
}
